# Basic
title: WangJace
#subtitle: A blog-orientation theme for Jekyll
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: iOS开发者，喜欢技术专研，运动爱好者
creator: <a href="http://blog.wangjace.site">@wangjace</a>

url: "http://wangjace.github.io"
# baseurl: '/'
domain: 'http://blog.wangjace.site'

permalink: /:year/:month/:title/

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: gray

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: wangjaces-blog
    
# Social
social:
    weibo: WangJace
    github: WangJace
    twitter: Jace_wcj
    gplus: 104433862847708362590
    linkedin: 傲云-王-852986100
    mail: wang-jace@foxmail.com

# Google Analytics
ga:
    id: UA-103802913-1
    host: auto

# Format
highlighter: rouge
