# Site setting
title: WangJace
description: iOS开发者，喜欢技术专研，运动爱好者
url: 'http://wangjace.github.io/' 
baseurl: '/'
domain: 'http://blog.wangjace.site'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'WangJace'
  email: wang-jace@foxmail.com
  twitter_username:  Jace_wcj
  github_username:  WangJace
  linkedin_username:  傲云-王-852986100
  description: WangJace's Blog

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
rouge: pygments
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  auto_ids: true

# Gems
gems: [jekyll-paginate]

exclude: ['RiADME.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
